server:
  port: 8081
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}


  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 8d0901001@smtp-brevo.com
    password: HxRFkEUyd0h7j5YW
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
