server:
  port: 8081
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
  ai:
     huggingface:
       chat:
         api-key: ${HUGGINGFACE_API_KEY}
         url: ${HUGGINGFACE_ENDPOINT_URL}
     azure:
      openai:
        api-key: ${AZURE_OPENAI_API_KEY}
        endpoint: ${AZURE_OPENAI_ENDPOINT}
      chat:
          options:
            deployment-name: ${AZURE_OPENAI_MODEL_NAME}

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 8d0901001@smtp-brevo.com
    password: HxRFkEUyd0h7j5YW
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
